apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod2
  labels: 
    app: myapp
    cloud: local
    location: NA
    type: frontend 
spec:  
  containers:
    - name: nginx-container 
      image: nginx 